FROM  node:current-alpine3.12

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

RUN ls

ENV NODE_ENV=production
ENV DBURL=

RUN command

COPY . .

EXPOSE 3001

CMD [ "npm", "prod" ]